// 자동 생성 파일 — 웨이트(Rider-Waite) 타로 78장 데이터
// 웹(PWA)과 React Native 양쪽에서 동일하게 import해서 사용합니다.
//
// image 필드는 https://lotto.smart-alba.com/images/taro/ 기준 상대 경로입니다.
// 폴더명은 실제 서버 폴더명 그대로입니다 (pentacles가 아니라 pantacles).
// 전체 URL이 필요하면 tarotImages.js의 tarotImageUrl(card)를 사용하세요.

export const FULL_DECK = [
  {
    "id": 0,
    "arcana": "major",
    "suit": null,
    "number": 0,
    "name_en": "The Fool",
    "name_ko": "바보",
    "upright_ko": "새로운 시작, 순수한 가능성, 자유로운 모험",
    "reversed_ko": "무모함, 경솔한 선택, 계획 없는 출발",
    "image": "major/00.png"
  },
  {
    "id": 1,
    "arcana": "major",
    "suit": null,
    "number": 1,
    "name_en": "The Magician",
    "name_ko": "마법사",
    "upright_ko": "의지의 실현, 창조적 능력, 갖춰진 자원",
    "reversed_ko": "속임수, 능력의 오용, 준비 부족",
    "image": "major/01.png"
  },
  {
    "id": 2,
    "arcana": "major",
    "suit": null,
    "number": 2,
    "name_en": "The High Priestess",
    "name_ko": "여사제",
    "upright_ko": "직관, 감춰진 지혜, 고요한 통찰",
    "reversed_ko": "비밀의 왜곡, 억눌린 직감, 판단 흐림",
    "image": "major/02.png"
  },
  {
    "id": 3,
    "arcana": "major",
    "suit": null,
    "number": 3,
    "name_en": "The Empress",
    "name_ko": "여황제",
    "upright_ko": "풍요, 창조성, 돌봄과 성장",
    "reversed_ko": "정체, 과잉보호, 창조력의 고갈",
    "image": "major/03.png"
  },
  {
    "id": 4,
    "arcana": "major",
    "suit": null,
    "number": 4,
    "name_en": "The Emperor",
    "name_ko": "황제",
    "upright_ko": "질서, 안정적 리더십, 확고한 구조",
    "reversed_ko": "독단, 경직된 통제, 권위의 남용",
    "image": "major/04.png"
  },
  {
    "id": 5,
    "arcana": "major",
    "suit": null,
    "number": 5,
    "name_en": "The Hierophant",
    "name_ko": "교황",
    "upright_ko": "전통, 가르침, 공동체의 규범",
    "reversed_ko": "관습에 대한 반발, 독단적 신념, 형식주의",
    "image": "major/05.png"
  },
  {
    "id": 6,
    "arcana": "major",
    "suit": null,
    "number": 6,
    "name_en": "The Lovers",
    "name_ko": "연인",
    "upright_ko": "선택과 조화, 진실한 유대",
    "reversed_ko": "불일치, 잘못된 선택, 관계의 균열",
    "image": "major/06.png"
  },
  {
    "id": 7,
    "arcana": "major",
    "suit": null,
    "number": 7,
    "name_en": "The Chariot",
    "name_ko": "전차",
    "upright_ko": "의지의 승리, 추진력, 목표 달성",
    "reversed_ko": "방향 상실, 통제력 부족, 무리한 강행",
    "image": "major/07.png"
  },
  {
    "id": 8,
    "arcana": "major",
    "suit": null,
    "number": 8,
    "name_en": "Strength",
    "name_ko": "힘",
    "upright_ko": "내면의 용기, 부드러운 통제, 인내",
    "reversed_ko": "자기 의심, 감정 통제 실패, 소진",
    "image": "major/08.png"
  },
  {
    "id": 9,
    "arcana": "major",
    "suit": null,
    "number": 9,
    "name_en": "The Hermit",
    "name_ko": "은둔자",
    "upright_ko": "성찰, 내적 탐구, 고독 속의 지혜",
    "reversed_ko": "고립, 회피, 소통 단절",
    "image": "major/09.png"
  },
  {
    "id": 10,
    "arcana": "major",
    "suit": null,
    "number": 10,
    "name_en": "Wheel of Fortune",
    "name_ko": "운명의 수레바퀴",
    "upright_ko": "전환점, 순환하는 운, 예상치 못한 기회",
    "reversed_ko": "불운의 반복, 통제 밖의 변화, 정체",
    "image": "major/10.png"
  },
  {
    "id": 11,
    "arcana": "major",
    "suit": null,
    "number": 11,
    "name_en": "Justice",
    "name_ko": "정의",
    "upright_ko": "공정함, 균형 잡힌 판단, 책임",
    "reversed_ko": "불공정, 편향된 결정, 회피하는 책임",
    "image": "major/11.png"
  },
  {
    "id": 12,
    "arcana": "major",
    "suit": null,
    "number": 12,
    "name_en": "The Hanged Man",
    "name_ko": "매달린 사람",
    "upright_ko": "관점의 전환, 기다림의 지혜, 내려놓음",
    "reversed_ko": "정체된 희생, 무의미한 지연, 저항",
    "image": "major/12.png"
  },
  {
    "id": 13,
    "arcana": "major",
    "suit": null,
    "number": 13,
    "name_en": "Death",
    "name_ko": "죽음",
    "upright_ko": "끝과 새로운 시작, 근본적 변화",
    "reversed_ko": "변화에 대한 저항, 정체, 미련",
    "image": "major/13.png"
  },
  {
    "id": 14,
    "arcana": "major",
    "suit": null,
    "number": 14,
    "name_en": "Temperance",
    "name_ko": "절제",
    "upright_ko": "균형과 조화, 인내심 있는 조율",
    "reversed_ko": "과잉과 결핍, 불균형, 조급함",
    "image": "major/14.png"
  },
  {
    "id": 15,
    "arcana": "major",
    "suit": null,
    "number": 15,
    "name_en": "The Devil",
    "name_ko": "악마",
    "upright_ko": "집착, 물질적 유혹, 속박된 욕망",
    "reversed_ko": "속박에서의 해방, 자각, 집착의 극복",
    "image": "major/15.png"
  },
  {
    "id": 16,
    "arcana": "major",
    "suit": null,
    "number": 16,
    "name_en": "The Tower",
    "name_ko": "탑",
    "upright_ko": "갑작스러운 붕괴, 각성, 충격적 전환",
    "reversed_ko": "위기의 지연, 두려움 속 회피, 작은 붕괴",
    "image": "major/16.png"
  },
  {
    "id": 17,
    "arcana": "major",
    "suit": null,
    "number": 17,
    "name_en": "The Star",
    "name_ko": "별",
    "upright_ko": "희망, 치유, 영감",
    "reversed_ko": "믿음의 상실, 낙담, 방향성 부재",
    "image": "major/17.png"
  },
  {
    "id": 18,
    "arcana": "major",
    "suit": null,
    "number": 18,
    "name_en": "The Moon",
    "name_ko": "달",
    "upright_ko": "불안, 무의식, 모호함 속의 직관",
    "reversed_ko": "혼란의 해소, 두려움의 극복, 진실의 발견",
    "image": "major/18.png"
  },
  {
    "id": 19,
    "arcana": "major",
    "suit": null,
    "number": 19,
    "name_en": "The Sun",
    "name_ko": "태양",
    "upright_ko": "성공, 활력, 순수한 기쁨",
    "reversed_ko": "일시적 좌절, 과도한 낙관, 지연된 성취",
    "image": "major/19.png"
  },
  {
    "id": 20,
    "arcana": "major",
    "suit": null,
    "number": 20,
    "name_en": "Judgement",
    "name_ko": "심판",
    "upright_ko": "각성, 재평가, 새로운 소명",
    "reversed_ko": "자기 비판, 후회, 결단의 지연",
    "image": "major/20.png"
  },
  {
    "id": 21,
    "arcana": "major",
    "suit": null,
    "number": 21,
    "name_en": "The World",
    "name_ko": "세계",
    "upright_ko": "완성, 성취, 하나의 순환의 끝",
    "reversed_ko": "미완성, 마무리 지연, 다음 단계로의 저항",
    "image": "major/21.png"
  },
  {
    "id": 22,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 1,
    "name_en": "ACE_OF_WANDS",
    "name_ko": "완드(지팡이) 에이스",
    "upright_ko": "새로운 시작의 씨앗이 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "새로운 시작의 씨앗이 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/01.png"
  },
  {
    "id": 23,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 2,
    "name_en": "TWO_OF_WANDS",
    "name_ko": "완드(지팡이) 2",
    "upright_ko": "균형과 선택의 기로가 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "균형과 선택의 기로가 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/02.png"
  },
  {
    "id": 24,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 3,
    "name_en": "THREE_OF_WANDS",
    "name_ko": "완드(지팡이) 3",
    "upright_ko": "협력과 확장이 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "협력과 확장이 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/03.png"
  },
  {
    "id": 25,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 4,
    "name_en": "FOUR_OF_WANDS",
    "name_ko": "완드(지팡이) 4",
    "upright_ko": "안정과 잠시의 휴식이 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "안정과 잠시의 휴식이 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/04.png"
  },
  {
    "id": 26,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 5,
    "name_en": "FIVE_OF_WANDS",
    "name_ko": "완드(지팡이) 5",
    "upright_ko": "갈등과 변화의 조짐이 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "갈등과 변화의 조짐이 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/05.png"
  },
  {
    "id": 27,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 6,
    "name_en": "SIX_OF_WANDS",
    "name_ko": "완드(지팡이) 6",
    "upright_ko": "조화와 회복이 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "조화와 회복이 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/06.png"
  },
  {
    "id": 28,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 7,
    "name_en": "SEVEN_OF_WANDS",
    "name_ko": "완드(지팡이) 7",
    "upright_ko": "인내와 재정비가 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "인내와 재정비가 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/07.png"
  },
  {
    "id": 29,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 8,
    "name_en": "EIGHT_OF_WANDS",
    "name_ko": "완드(지팡이) 8",
    "upright_ko": "빠른 움직임과 진전이 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "빠른 움직임과 진전이 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/08.png"
  },
  {
    "id": 30,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 9,
    "name_en": "NINE_OF_WANDS",
    "name_ko": "완드(지팡이) 9",
    "upright_ko": "결실을 앞둔 긴장이 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "결실을 앞둔 긴장이 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/09.png"
  },
  {
    "id": 31,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 10,
    "name_en": "TEN_OF_WANDS",
    "name_ko": "완드(지팡이) 10",
    "upright_ko": "완성과 다음 단계로의 전환이 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "완성과 다음 단계로의 전환이 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/10.png"
  },
  {
    "id": 32,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 11,
    "name_en": "PAGE_OF_WANDS",
    "name_ko": "완드(지팡이) 페이지",
    "upright_ko": "배움과 호기심 가득한 초심이 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "배움과 호기심 가득한 초심이 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/11.png"
  },
  {
    "id": 33,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 12,
    "name_en": "KNIGHT_OF_WANDS",
    "name_ko": "완드(지팡이) 나이트",
    "upright_ko": "행동과 추진력이 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "행동과 추진력이 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/12.png"
  },
  {
    "id": 34,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 13,
    "name_en": "QUEEN_OF_WANDS",
    "name_ko": "완드(지팡이) 퀸",
    "upright_ko": "성숙한 포용과 통찰이 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "성숙한 포용과 통찰이 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/13.png"
  },
  {
    "id": 35,
    "arcana": "minor",
    "suit": "wands",
    "suit_name_ko": "완드(지팡이)",
    "element": "불",
    "number": 14,
    "name_en": "KING_OF_WANDS",
    "name_ko": "완드(지팡이) 킹",
    "upright_ko": "완숙한 통제력과 권위가 열정과 행동력, 창조적 에너지의 형태로 나타납니다.",
    "reversed_ko": "완숙한 통제력과 권위가 막히거나 뒤틀려, 조급함과 방향을 잃은 에너지로 드러납니다.",
    "image": "wands/14.png"
  },
  {
    "id": 36,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 1,
    "name_en": "ACE_OF_CUPS",
    "name_ko": "컵(성배) 에이스",
    "upright_ko": "새로운 시작의 씨앗이 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "새로운 시작의 씨앗이 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/01.png"
  },
  {
    "id": 37,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 2,
    "name_en": "TWO_OF_CUPS",
    "name_ko": "컵(성배) 2",
    "upright_ko": "균형과 선택의 기로가 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "균형과 선택의 기로가 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/02.png"
  },
  {
    "id": 38,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 3,
    "name_en": "THREE_OF_CUPS",
    "name_ko": "컵(성배) 3",
    "upright_ko": "협력과 확장이 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "협력과 확장이 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/03.png"
  },
  {
    "id": 39,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 4,
    "name_en": "FOUR_OF_CUPS",
    "name_ko": "컵(성배) 4",
    "upright_ko": "안정과 잠시의 휴식이 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "안정과 잠시의 휴식이 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/04.png"
  },
  {
    "id": 40,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 5,
    "name_en": "FIVE_OF_CUPS",
    "name_ko": "컵(성배) 5",
    "upright_ko": "갈등과 변화의 조짐이 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "갈등과 변화의 조짐이 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/05.png"
  },
  {
    "id": 41,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 6,
    "name_en": "SIX_OF_CUPS",
    "name_ko": "컵(성배) 6",
    "upright_ko": "조화와 회복이 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "조화와 회복이 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/06.png"
  },
  {
    "id": 42,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 7,
    "name_en": "SEVEN_OF_CUPS",
    "name_ko": "컵(성배) 7",
    "upright_ko": "인내와 재정비가 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "인내와 재정비가 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/07.png"
  },
  {
    "id": 43,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 8,
    "name_en": "EIGHT_OF_CUPS",
    "name_ko": "컵(성배) 8",
    "upright_ko": "빠른 움직임과 진전이 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "빠른 움직임과 진전이 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/08.png"
  },
  {
    "id": 44,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 9,
    "name_en": "NINE_OF_CUPS",
    "name_ko": "컵(성배) 9",
    "upright_ko": "결실을 앞둔 긴장이 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "결실을 앞둔 긴장이 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/09.png"
  },
  {
    "id": 45,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 10,
    "name_en": "TEN_OF_CUPS",
    "name_ko": "컵(성배) 10",
    "upright_ko": "완성과 다음 단계로의 전환이 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "완성과 다음 단계로의 전환이 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/10.png"
  },
  {
    "id": 46,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 11,
    "name_en": "PAGE_OF_CUPS",
    "name_ko": "컵(성배) 페이지",
    "upright_ko": "배움과 호기심 가득한 초심이 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "배움과 호기심 가득한 초심이 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/11.png"
  },
  {
    "id": 47,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 12,
    "name_en": "KNIGHT_OF_CUPS",
    "name_ko": "컵(성배) 나이트",
    "upright_ko": "행동과 추진력이 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "행동과 추진력이 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/12.png"
  },
  {
    "id": 48,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 13,
    "name_en": "QUEEN_OF_CUPS",
    "name_ko": "컵(성배) 퀸",
    "upright_ko": "성숙한 포용과 통찰이 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "성숙한 포용과 통찰이 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/13.png"
  },
  {
    "id": 49,
    "arcana": "minor",
    "suit": "cups",
    "suit_name_ko": "컵(성배)",
    "element": "물",
    "number": 14,
    "name_en": "KING_OF_CUPS",
    "name_ko": "컵(성배) 킹",
    "upright_ko": "완숙한 통제력과 권위가 감정과 관계, 직관의 흐름의 형태로 나타납니다.",
    "reversed_ko": "완숙한 통제력과 권위가 막히거나 뒤틀려, 감정 기복과 소통의 단절로 드러납니다.",
    "image": "cups/14.png"
  },
  {
    "id": 50,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 1,
    "name_en": "ACE_OF_SWORDS",
    "name_ko": "소드(검) 에이스",
    "upright_ko": "새로운 시작의 씨앗이 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "새로운 시작의 씨앗이 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/01.png"
  },
  {
    "id": 51,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 2,
    "name_en": "TWO_OF_SWORDS",
    "name_ko": "소드(검) 2",
    "upright_ko": "균형과 선택의 기로가 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "균형과 선택의 기로가 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/02.png"
  },
  {
    "id": 52,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 3,
    "name_en": "THREE_OF_SWORDS",
    "name_ko": "소드(검) 3",
    "upright_ko": "협력과 확장이 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "협력과 확장이 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/03.png"
  },
  {
    "id": 53,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 4,
    "name_en": "FOUR_OF_SWORDS",
    "name_ko": "소드(검) 4",
    "upright_ko": "안정과 잠시의 휴식이 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "안정과 잠시의 휴식이 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/04.png"
  },
  {
    "id": 54,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 5,
    "name_en": "FIVE_OF_SWORDS",
    "name_ko": "소드(검) 5",
    "upright_ko": "갈등과 변화의 조짐이 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "갈등과 변화의 조짐이 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/05.png"
  },
  {
    "id": 55,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 6,
    "name_en": "SIX_OF_SWORDS",
    "name_ko": "소드(검) 6",
    "upright_ko": "조화와 회복이 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "조화와 회복이 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/06.png"
  },
  {
    "id": 56,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 7,
    "name_en": "SEVEN_OF_SWORDS",
    "name_ko": "소드(검) 7",
    "upright_ko": "인내와 재정비가 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "인내와 재정비가 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/07.png"
  },
  {
    "id": 57,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 8,
    "name_en": "EIGHT_OF_SWORDS",
    "name_ko": "소드(검) 8",
    "upright_ko": "빠른 움직임과 진전이 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "빠른 움직임과 진전이 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/08.png"
  },
  {
    "id": 58,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 9,
    "name_en": "NINE_OF_SWORDS",
    "name_ko": "소드(검) 9",
    "upright_ko": "결실을 앞둔 긴장이 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "결실을 앞둔 긴장이 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/09.png"
  },
  {
    "id": 59,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 10,
    "name_en": "TEN_OF_SWORDS",
    "name_ko": "소드(검) 10",
    "upright_ko": "완성과 다음 단계로의 전환이 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "완성과 다음 단계로의 전환이 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/10.png"
  },
  {
    "id": 60,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 11,
    "name_en": "PAGE_OF_SWORDS",
    "name_ko": "소드(검) 페이지",
    "upright_ko": "배움과 호기심 가득한 초심이 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "배움과 호기심 가득한 초심이 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/11.png"
  },
  {
    "id": 61,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 12,
    "name_en": "KNIGHT_OF_SWORDS",
    "name_ko": "소드(검) 나이트",
    "upright_ko": "행동과 추진력이 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "행동과 추진력이 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/12.png"
  },
  {
    "id": 62,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 13,
    "name_en": "QUEEN_OF_SWORDS",
    "name_ko": "소드(검) 퀸",
    "upright_ko": "성숙한 포용과 통찰이 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "성숙한 포용과 통찰이 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/13.png"
  },
  {
    "id": 63,
    "arcana": "minor",
    "suit": "swords",
    "suit_name_ko": "소드(검)",
    "element": "공기",
    "number": 14,
    "name_en": "KING_OF_SWORDS",
    "name_ko": "소드(검) 킹",
    "upright_ko": "완숙한 통제력과 권위가 생각과 논리, 도전 속의 결단의 형태로 나타납니다.",
    "reversed_ko": "완숙한 통제력과 권위가 막히거나 뒤틀려, 혼란과 스트레스, 흐려진 시야로 드러납니다.",
    "image": "swords/14.png"
  },
  {
    "id": 64,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 1,
    "name_en": "ACE_OF_PENTACLES",
    "name_ko": "펜타클(금화) 에이스",
    "upright_ko": "새로운 시작의 씨앗이 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "새로운 시작의 씨앗이 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/01.png"
  },
  {
    "id": 65,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 2,
    "name_en": "TWO_OF_PENTACLES",
    "name_ko": "펜타클(금화) 2",
    "upright_ko": "균형과 선택의 기로가 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "균형과 선택의 기로가 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/02.png"
  },
  {
    "id": 66,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 3,
    "name_en": "THREE_OF_PENTACLES",
    "name_ko": "펜타클(금화) 3",
    "upright_ko": "협력과 확장이 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "협력과 확장이 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/03.png"
  },
  {
    "id": 67,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 4,
    "name_en": "FOUR_OF_PENTACLES",
    "name_ko": "펜타클(금화) 4",
    "upright_ko": "안정과 잠시의 휴식이 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "안정과 잠시의 휴식이 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/04.png"
  },
  {
    "id": 68,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 5,
    "name_en": "FIVE_OF_PENTACLES",
    "name_ko": "펜타클(금화) 5",
    "upright_ko": "갈등과 변화의 조짐이 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "갈등과 변화의 조짐이 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/05.png"
  },
  {
    "id": 69,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 6,
    "name_en": "SIX_OF_PENTACLES",
    "name_ko": "펜타클(금화) 6",
    "upright_ko": "조화와 회복이 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "조화와 회복이 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/06.png"
  },
  {
    "id": 70,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 7,
    "name_en": "SEVEN_OF_PENTACLES",
    "name_ko": "펜타클(금화) 7",
    "upright_ko": "인내와 재정비가 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "인내와 재정비가 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/07.png"
  },
  {
    "id": 71,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 8,
    "name_en": "EIGHT_OF_PENTACLES",
    "name_ko": "펜타클(금화) 8",
    "upright_ko": "빠른 움직임과 진전이 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "빠른 움직임과 진전이 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/08.png"
  },
  {
    "id": 72,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 9,
    "name_en": "NINE_OF_PENTACLES",
    "name_ko": "펜타클(금화) 9",
    "upright_ko": "결실을 앞둔 긴장이 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "결실을 앞둔 긴장이 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/09.png"
  },
  {
    "id": 73,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 10,
    "name_en": "TEN_OF_PENTACLES",
    "name_ko": "펜타클(금화) 10",
    "upright_ko": "완성과 다음 단계로의 전환이 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "완성과 다음 단계로의 전환이 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/10.png"
  },
  {
    "id": 74,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 11,
    "name_en": "PAGE_OF_PENTACLES",
    "name_ko": "펜타클(금화) 페이지",
    "upright_ko": "배움과 호기심 가득한 초심이 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "배움과 호기심 가득한 초심이 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/11.png"
  },
  {
    "id": 75,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 12,
    "name_en": "KNIGHT_OF_PENTACLES",
    "name_ko": "펜타클(금화) 나이트",
    "upright_ko": "행동과 추진력이 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "행동과 추진력이 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/12.png"
  },
  {
    "id": 76,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 13,
    "name_en": "QUEEN_OF_PENTACLES",
    "name_ko": "펜타클(금화) 퀸",
    "upright_ko": "성숙한 포용과 통찰이 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "성숙한 포용과 통찰이 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/13.png"
  },
  {
    "id": 77,
    "arcana": "minor",
    "suit": "pentacles",
    "suit_name_ko": "펜타클(금화)",
    "element": "흙",
    "number": 14,
    "name_en": "KING_OF_PENTACLES",
    "name_ko": "펜타클(금화) 킹",
    "upright_ko": "완숙한 통제력과 권위가 현실과 물질, 재정적 안정의 형태로 나타납니다.",
    "reversed_ko": "완숙한 통제력과 권위가 막히거나 뒤틀려, 불안정과 낭비, 현실 도피로 드러납니다.",
    "image": "pantacles/14.png"
  }
];

export const MAJOR_COUNT = 22;
export const TOTAL_COUNT = 78;
